%--------------------------------------------------
%   Author: Michael Strasser
%   Helmholtz Zentrum München
%   Institute of Computational Biology
%   http://www.helmholtz-muenchen.de/icb/
%   09/2015
%--------------------------------------------------

addpath(genpath('algorithm'))
addpath(genpath('utils'))
addpath(genpath('plotting'))

%% how does tracking error influence the model validation via sister correlations
% for each amount of tracking error, we perform the feature
% selection and based on these features, we predict the expected number of sister pairs, yielding a
% pvalue (chi2 test). 
% To reduce the randomness, this is repeated 10times (per amount of tracking error),
% but making sure that the trees of the 10 runs do not intersect!

% Computation has been run on a cluster to reduce computational time
% 1. inputs for each job where generated by a single call of "createInputs_4_featureSelection_vs_trackingError()"
% 2. each job ran qJob_sisterCorr_trackingError() on a single input
%
% for details see 'qJob_sisterCorr_trackingError()'
%
% here only the results of the calculations are considered
load data/trackingError/trackingErrorSisters_tophat.mat aggr_outputs

trackingErrorVector = [0.001 0.005 0.01 0.015 0.02 0.05 0 0.1 0.03 0.04 0.06 0.07 0.08 0.09 0.1];

nRepeats = 10;

pvalues = zeros(length(trackingErrorVector),nRepeats);
counter = 1;
for i = 1:length(trackingErrorVector)
    pTrackingError = trackingErrorVector(i);
    for j = 1:nRepeats %repeats
        pvalues(i,j)=    aggr_outputs{counter}.pval_true;
        counter = counter+1;
    end
end
% trackign error is not yet sorted in ascending order
[trackingErrorVector,ix_sort] = sort(trackingErrorVector);
pvalues = pvalues(ix_sort,:);

%last one (error =0.1) is double (calculated twice)
trackingErrorVector = trackingErrorVector(1:end-1);
pvalues = pvalues(1:end-1,:);

%% plotting

logMean = mean(log10(pvalues),2);
logStd = std(log10(pvalues),[],2);
figure;shadedErrorBar(trackingErrorVector.*100,logMean,logStd,'k');
hline(log10(0.05),'k--')
xlabel('Tracking error (fraction of cells) in percent'); ylabel('log_{10}(p) (x^2 test)')
box off
set(gca,'YTick',[-4 -3 -2 -1 0])

